org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


#neoforge
minecraft_version=26.1
minecraft_version_range=[26.1,26.1]
neo_version=26.1.0.19-beta
neoforge_version_range=[26.1.0.19-beta,)


#remove if you did not have proxy
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808


#mod
mod_id=easylogin
mod_name=EasyLogin
mod_license=AGPL-v3
mod_version=1.2.0
mod_group_id=cn.thesilentnights.easylogin
mod_authors=TheSilentNights
mod_description= a server side mod provides player auth